---
title: "data-exploration"
editor: visual
---

```{r}
library(arrow)
library(ggplot2)
library(dplyr)
library(lubridate)

df <- read_parquet("data/complete_weather_and_taxi_data.parquet")
```

```{r}
dfsum <- df |> 
  mutate(day=wday(date),
         month=month(date),
         year=year(date)) |> 
  group_by(year,month,day) |>
  summarize(avg_trips = mean(trip_count))
```

```{r}
head(dfsum)
```

```{r}
ggplot(dfsum, aes(x=as.factor(day), y=as.factor(month), fill=avg_trips)) +
         geom_tile(color="white") + 
         scale_fill_gradient(low = "white", high = "red", name = "N trips") +
         labs(
          title = "Avg trips day of week",
          x = "Day of week",
          y=month) +
        theme_classic() 
```

```{r}
df |> 
  mutate(day = wday(date, label = TRUE),
         year = year(date)) |> 
  ggplot(aes(x=day, y=trip_count))+
  geom_boxplot() +
  facet_wrap(~year)
```

```{r}
df |> 
  mutate(month = month(date, label = TRUE),
         year = year(date)) |> 
  ggplot(aes(x=month, y=trip_count))+
  geom_boxplot() +
  facet_wrap(~year)
```

```{r}
dfsum <- df |> 
  mutate(day = wday(date, label = TRUE), 
         month = month(date, label = TRUE),
         year = year(date)) |> 
  group_by(year, month, day) |>
  summarize(avg_trips = mean(trip_count), .groups = 'drop')

ggplot(dfsum, aes(x = day, y = month, fill = avg_trips)) +
  geom_tile(color = "white") + 
  scale_fill_gradient(low = "white", high = "red", name = "Avg Trips") +
  labs(
    title = "Average Trips by Day of the Week and Month",
    x = "Day of the Week",
    y = "Month"
  ) +
  theme_classic()

```

```{r}
dfsum <- df |> 
  mutate(day = wday(date, label = TRUE), 
         month = month(date, label = TRUE),
         year = year(date)) |> 
  group_by(year, month, day) |>
  summarize(avg_trips = mean(trip_count), .groups = 'drop')

ggplot(dfsum, aes(x = day, y = month, fill = avg_trips)) +
  geom_tile(color = "white") + 
  scale_fill_gradient(low = "white", high = "red", name = "Avg Trips") +
  labs(
    title = "Average Trips by Day of the Week and Month",
    x = "Day of the Week",
    y = "Month"
  ) +
  theme_classic() +
  facet_wrap(~year, ncol=6)
```

```{r}
dfsum <- df |> 
  mutate(day = wday(date, label = TRUE))|> 
  group_by(day, hour) |>
  summarize(avg_trips = mean(trip_count), .groups = 'drop')

ggplot(dfsum, aes(x = day, y = hour, fill = avg_trips)) +
  geom_tile(color = "white") + 
  scale_fill_gradient(low = "white", high = "red", name = "Avg Trips") +
  labs(
    title = "Average Trips by Day of the Week and Hour",
    x = "Day of the Week",
    y = "Hour"
  ) +
  theme_classic()
```

```{r}
dfsum <- df |> 
  mutate(day=wday(date),
         month=month(date),
         year=year(date)) |> 
  group_by(year,month,day) |>
  summarize(avg_trips = mean(trip_count))
```

```{r}
df |> 
  ggplot(aes(x=trip_distance_median, y=fare_amount_median)) +
  geom_point()
```

```{r}
df |> filter(is.na(trip_distance_median))
```

```{r}
head(df)
```

```{r}
head(df, 30)
```

```{r}
boxplot(x=df$trip_count)
```

```{r}
df |> 
  ggplot(aes(x=trip_distance_mean)) + geom_histogram(binwidth=0.5)
```

```{r}
quantile(df$trip_distance_mean, na.rm=TRUE)
```

```{r}
df$rain <- as.factor(ifelse(df$precipitation != 0, "Raining", "Not raining"))
df |> filter(rain=="Raining") |>  nrow()
  
```

```{r}
df |> 
  group_by(rain) |> 
  summarize(mean_ct = mean(trip_count))
```

```{r}
df |> 
  group_by(pres_wx_AU1)
```

```{r}

```

`{|>}   summarize(mean_rain=mean(precipitation)) |>    print()`

```{r}
df |> 
  filter(pres_wx_AU1 == "-RA:02") |> 
  nrow()
```

```{r}

```
