<!-- ## Weather vs. Trips. -->

Now that we have refocused our attention to a smaller subset of the data, 
we can look at some initial relationships between the two central 
taxi variables (`trip_count` and the various distance bands) and the three
weather variables, (`temperature`, `cloud_cover`, and `rain`).

```{r}
df |>
  mutate(
    temperature = round(temperature)
  ) |>
  mutate(
    up_to_ten_mile_trips = trip_count - rowSums(across(ends_with("mile_trips")))
  ) |>
  pivot_longer(
    cols=c(ends_with("mile_trips")),
    names_to="trip_type",
    values_to="trip_type_count",
  ) |>
  mutate(trip_type = factor(trip_type, 
    levels = c(
      "half_mile_trips", 
      "one_mile_trips", 
      "two_mile_trips", 
      "three_mile_trips", 
      "five_mile_trips", 
      "up_to_ten_mile_trips"
      ),
    labels = c(
      "Up to Half-Mile Trips",
      "Up to One-Mile Trips",
      "Up to Two-Mile Trips",
      "Up to Three-Mile Trips",
      "Up to Five-Mile Trips",
      "Up to Ten-Mile Trips"
    ),
    ordered = TRUE)) |>
  group_by(trip_type, temperature) |>
  summarize(
    avg_trips_by_degree=mean(trip_type_count),
    .groups = "drop"
  ) |>
  ggplot(aes(temperature, avg_trips_by_degree)) +
    geom_point(color=base_color, size=1, alpha=0.5) +
    scale_y_continuous(
      labels = thousands,
      breaks = pretty_breaks(n = 3)
    ) +
    geom_smooth(color=secondary_color, method="loess", linewidth=1, se=TRUE, alpha=0.15)+
    # scale_fill_distiller(
    #   palette = "GnBu"
    # ) +
    labs(
      title = "Average Hourly Trips Per Hour by Integral Temperature across Trip Distance",
      y = "Average Hourly Trips",
      x = temp_label,
      fill = "Count"
    ) +
  facet_wrap(~ trip_type, ncol = 3, nrow = 2, scales="free_y")
```


```{r}
df |>
  mutate(
    up_to_ten_mile_trips = trip_count - rowSums(across(ends_with("mile_trips")))
  ) |>
  pivot_longer(
    cols=c(ends_with("mile_trips")),
    names_to="trip_type",
    values_to="trip_type_count",
  ) |>
  mutate(trip_type = factor(trip_type, 
    levels = c(
      "half_mile_trips", 
      "one_mile_trips", 
      "two_mile_trips", 
      "three_mile_trips", 
      "five_mile_trips", 
      "up_to_ten_mile_trips"
      ),
    labels = c(
      "Up to Half-Mile Trips",
      "Up to One-Mile Trips",
      "Up to Two-Mile Trips",
      "Up to Three-Mile Trips",
      "Up to Five-Mile Trips",
      "Up to Ten-Mile Trips"
    ),
    ordered = TRUE)) |>
  group_by(trip_type, cloud_cover) |> 
  summarize(
    avg_trips = mean(trip_type_count, na.rm = TRUE),
    se = sd(trip_type_count, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  ) |>
  ggplot(aes(x = cloud_cover, y = avg_trips, fill = cloud_cover)) +
  geom_bar(stat = "identity", position = "dodge") +
  # geom_errorbar(aes(ymin = avg_trips - se, ymax = avg_trips + se), 
  #               width = 0.2, position = position_dodge(0.9)) +
  facet_wrap(~trip_type, scales = "free_y") +
  scale_y_continuous(label=comma)+
  scale_fill_brewer(palette = "GnBu") +
  labs(
    title = "Average Hourly Trips by Cloud Cover and Trip Distance",
    x = "Cloud Cover",
    y = "Average Hourly Trips",
    fill = "Cloud Cover"
  )+
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    legend.position = "bottom" 
 ) 
```

```{r}
df |>
  mutate(
    up_to_ten_mile_trips = trip_count - rowSums(across(ends_with("mile_trips")))
  ) |>
  pivot_longer(
    cols=c(ends_with("mile_trips")),
    names_to="trip_type",
    values_to="trip_type_count",
  ) |>
  mutate(trip_type = factor(trip_type, 
    levels = c(
      "half_mile_trips", 
      "one_mile_trips", 
      "two_mile_trips", 
      "three_mile_trips", 
      "five_mile_trips", 
      "up_to_ten_mile_trips"
      ),
    labels = c(
      "Up to Half-Mile Trips",
      "Up to One-Mile Trips",
      "Up to Two-Mile Trips",
      "Up to Three-Mile Trips",
      "Up to Five-Mile Trips",
      "Up to Ten-Mile Trips"
    ),
    ordered = TRUE)) |>
  group_by(trip_type, rain) |> 
  summarize(
    avg_trips = mean(trip_type_count, na.rm = TRUE),
    se = sd(trip_type_count, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  ) |>
  ggplot(aes(x = rain, y = avg_trips, fill = rain)) +
  geom_bar(stat = "identity", position = "dodge") +
  # geom_errorbar(aes(ymin = avg_trips - se, ymax = avg_trips + se),
  #               width = 0.2, position = position_dodge(0.9)) +
  facet_wrap(~trip_type, scales = "free_y") +
  scale_y_continuous(label=comma)+
  scale_fill_brewer(palette = "Set2") +
  labs(
    title = "Average Hourly Trips by Rain and Trip Distance",
    x = "Rain",
    y = "Average Hourly Trips",
    fill = "Rain"
  )+
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    legend.position = "bottom" 
 ) 
```

